### ISSUE TITLE
Drone issue

### ISSUE THREAD

**Issue by bgervan** [caprover/one-click-apps#113]
1.0.0-rc.6 This version is not available yet.
The error message I got.
```
December 21st 2019, 4:35:27.736 pm    Error: (HTTP code 404) unexpected - manifest for drone/drone:1.0.0-rc.6 not found: manifest unknown: manifest unknown
captain-captain.1.rfxsnrsgga2f@vmi329170.contaboserver.net    | Error: (HTTP code 404) unexpected - manifest for drone/drone:1.0.0-rc.6 not found: manifest unknown: manifest unknown
captain-captain.1.rfxsnrsgga2f@vmi329170.contaboserver.net    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:257:17
captain-captain.1.rfxsnrsgga2f@vmi329170.contaboserver.net    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:9)
captain-captain.1.rfxsnrsgga2f@vmi329170.contaboserver.net    |     at IncomingMessage.emit (events.js:203:15)
captain-captain.1.rfxsnrsgga2f@vmi329170.contaboserver.net    |     at endReadableNT (_stream_readable.js:1143:12)
captain-captain.1.rfxsnrsgga2f@vmi329170.contaboserver.net    |     at process._tickCallback (internal/process/next_tick.js:63:19)
```
The agent exists, but the server is not. With rc5 version, it works fine. I had to investigate a little, because I am new to caprover, until they release this version for docker hub, the default value should remain rc5. Or at least they could find this issue, and they could resolve easier.

**Comment by githubsaturn** [comment]
Please feel free to open a PR and edit the definition here:
https://github.com/caprover/one-click-apps/blob/master/public/v2/apps/drone-gitea.json
