### ISSUE TITLE
[BUG] Keycloak Deploying DB Error

### ISSUE THREAD

**Issue by suphero** [caprover/one-click-apps#290]
I am getting an error while creating one click keycloak app. It fails in Deploying keycloak-db step with "Failed: Error: Request failed with status code 500" message.

CapRover version: 1.8.0

<img width="662" alt="Screen Shot 2020-10-26 at 22 03 42" src="https://user-images.githubusercontent.com/846531/97216595-23258100-17d7-11eb-9ec8-0304176a8045.png">
 
Related Logs:
```
captain    | October 27th 2020, 5:56:02.323 am    retrieving app at: https://oneclickapps.caprover.com/v4/apps/keycloak
captain    | GET /api/v2/user/oneclick/template/app?appName=keycloak&baseDomain=https:%2F%2Foneclickapps.caprover.com 304 121.324 ms - -
captain    | GET /api/v2/user/system/info 304 1.609 ms - -
captain    | October 27th 2020, 5:56:21.866 am    Registering app started: keycloak-db
captain    | October 27th 2020, 5:56:21.903 am    Building docker image. This might take a few minutes...
captain    | October 27th 2020, 5:56:22.210 am    Ensure service inited and Updated for: keycloak-db
captain    | October 27th 2020, 5:56:22.214 am    Check if service is running: srv-captain--keycloak-db
captain    | October 27th 2020, 5:56:22.218 am    Creating service srv-captain--keycloak-db with default image, we will update image later
captain    | October 27th 2020, 5:56:22.232 am    Updating service srv-captain--keycloak-db with image img-captain-keycloak-db:0
captain    | October 27th 2020, 5:56:24.249 am    Updating Load Balancer - ServiceManager
captain    | October 27th 2020, 5:56:24.259 am    Locking NGINX configuration reloading...
captain    | October 27th 2020, 5:56:24.296 am    SUCCESS: UNLocking NGINX configuration reloading...
captain    | October 27th 2020, 5:56:24.297 am    sendReloadSignal...
captain    | October 27th 2020, 5:56:24.314 am    Kill HUP Container: 33738f47550359f74686c6aea2477cc780d5aab21d677a1f0affa14dd04d3103
captain    | October 27th 2020, 5:56:24.340 am    AppName is saved: keycloak-db
captain    | POST /api/v2/user/apps/appDefinitions/register 200 2475.695 ms - 61
captain    | GET /api/v2/user/apps/appDefinitions 200 6.191 ms - 21619
captain    | October 27th 2020, 5:56:24.713 am    Updating app started: keycloak-db
captain    | October 27th 2020, 5:56:24.727 am    Ensure service inited and Updated for: keycloak-db
captain    | October 27th 2020, 5:56:24.729 am    Check if service is running: srv-captain--keycloak-db
captain    | October 27th 2020, 5:56:24.736 am    Service is already running: srv-captain--keycloak-db
captain    | October 27th 2020, 5:56:24.736 am    Updating service srv-captain--keycloak-db with image img-captain-keycloak-db:0
captain    | October 27th 2020, 5:56:26.747 am    Updating Load Balancer - ServiceManager
captain    | October 27th 2020, 5:56:26.747 am    Locking NGINX configuration reloading...
captain    | October 27th 2020, 5:56:26.760 am    SUCCESS: UNLocking NGINX configuration reloading...
captain    | October 27th 2020, 5:56:26.760 am    sendReloadSignal...
captain    | October 27th 2020, 5:56:26.763 am    Kill HUP Container: 33738f47550359f74686c6aea2477cc780d5aab21d677a1f0affa14dd04d3103
captain    | October 27th 2020, 5:56:26.788 am    Updating Load Balancer - ServiceManager
captain    | October 27th 2020, 5:56:26.788 am    Locking NGINX configuration reloading...
captain    | October 27th 2020, 5:56:26.797 am    SUCCESS: UNLocking NGINX configuration reloading...
captain    | October 27th 2020, 5:56:26.797 am    sendReloadSignal...
captain    | October 27th 2020, 5:56:26.800 am    Kill HUP Container: 33738f47550359f74686c6aea2477cc780d5aab21d677a1f0affa14dd04d3103
captain    | October 27th 2020, 5:56:26.818 am    AppName is updated: keycloak-db
captain    | POST /api/v2/user/apps/appDefinitions/update 200 2109.580 ms - 69
captain    | October 27th 2020, 5:56:27.098 am    Error: (HTTP code 500) server error - Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution 
captain    | Error: (HTTP code 500) server error - Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution 
captain    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
captain    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:328:9)
captain    |     at IncomingMessage.emit (events.js:326:22)
captain    |     at endReadableNT (_stream_readable.js:1244:12)
captain    |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
captain    | POST /api/v2/user/apps/appData/keycloak-db 500 18.864 ms - 21
captain    | October 27th 2020, 5:56:27.240 am    Pruning containers...
```

**Comment by githubsaturn** [comment]
While this happen, please get the logs from your server by running
```
docker service logs captain-captain --since 5m
```
and copy the logs here for further inspection.

**Comment by suphero** [comment]
I have added logs to the issue

**Comment by githubsaturn** [comment]
Looks like you have a DNS issue:
```
dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
```

Do other one click apps work?


Also, have a look at this: https://www.digitalocean.com/community/questions/how-to-resolve-temporary-failure-in-name-resolution-issue

**Comment by suphero** [comment]
You are right, the issue was about the DNS and it is solved by using [resolvconf service](https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/). Thanks for your support.
