### ISSUE TITLE
Issue with one-click Mastodon setup

### ISSUE THREAD

**Issue by icarusredux** [caprover/one-click-apps#350]
I've successfully gotten the Dockerized Mastodon v3.3.0 to mostly get up and running as a one-click install. However, I'm unable to upload images (422 error), and I get the following errors in the log files:

Sidekiq:
```
2021-01-17T18:12:45.451Z pid=9 tid=3ck9 WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","dead":false,"class":"PostProcessMediaWorker","args":[105572410239496182],"jid":"7e8072cfaec528ddbdcf01f8","created_at":1610907138.7121584,"enqueued_at":1610907165.4169474,"error_message":"No such file or directory @ rb_sysopen - /opt/mastodon/public/system/media_attachments/files/105/572/410/239/496/182/original/f2c7e92331ad3e9d.png","error_class":"Errno::ENOENT","failed_at":1610907138.7921062,"retry_count":0},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"dead\":false,\"class\":\"PostProcessMediaWorker\",\"args\":[105572410239496182],\"jid\":\"7e8072cfaec528ddbdcf01f8\",\"created_at\":1610907138.7121584,\"enqueued_at\":1610907165.4169474,\"error_message\":\"No such file or directory @ rb_sysopen - /opt/mastodon/public/system/media_attachments/files/105/572/410/239/496/182/original/f2c7e92331ad3e9d.png\",\"error_class\":\"Errno::ENOENT\",\"failed_at\":1610907138.7921062,\"retry_count\":0}"}
2021-01-17T18:12:45.451Z pid=9 tid=3ck9 WARN: Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/mastodon/public/system/media_attachments/files/105/572/410/239/496/182/original/f2c7e92331ad3e9d.png
2021-01-17T18:12:45.452Z pid=9 tid=3ck9 WARN: /opt/ruby/lib/ruby/2.7.0/fileutils.rb:1414:in `initialize'
/opt/ruby/lib/ruby/2.7.0/fileutils.rb:1414:in `open'
/opt/ruby/lib/ruby/2.7.0/fileutils.rb:1414:in `copy_file'
```

Mastodon has the 422 of course:
```
[cc93498a-5879-44bc-9371-bc20b067893b] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=16.13 view=1.32 db=2.65
[dcb504ed-4cac-46be-8e21-449d0e83a76f] [paperclip] Trying to link /tmp/RackMultipart20210117-16-1iy49fj.gif to /tmp/79269964c701fef64784613189e8af2520210117-16-aefhp8.gif
[dcb504ed-4cac-46be-8e21-449d0e83a76f] [paperclip] Trying to link /tmp/79269964c701fef64784613189e8af2520210117-16-aefhp8.gif to /tmp/6984c25bbd7555995aadc00f2bb58a7320210117-16-1a9osbt.gif
[dcb504ed-4cac-46be-8e21-449d0e83a76f] Command :: file -b --mime '/tmp/6984c25bbd7555995aadc00f2bb58a7320210117-16-1a9osbt.gif'
[dcb504ed-4cac-46be-8e21-449d0e83a76f] Command :: convert '/tmp/79269964c701fef64784613189e8af2520210117-16-aefhp8.gif' RGB:-
[dcb504ed-4cac-46be-8e21-449d0e83a76f] [paperclip] Trying to link /tmp/79269964c701fef64784613189e8af2520210117-16-aefhp8.gif to /tmp/9698731b54db5d8177d49ecf624ae02120210117-16-12hsvqz.gif
[dcb504ed-4cac-46be-8e21-449d0e83a76f] [paperclip] Trying to link /tmp/79269964c701fef64784613189e8af2520210117-16-aefhp8.gif to /tmp/6984c25bbd7555995aadc00f2bb58a7320210117-16-frnxl6.gif
[dcb504ed-4cac-46be-8e21-449d0e83a76f] Command :: file -b --mime '/tmp/6984c25bbd7555995aadc00f2bb58a7320210117-16-frnxl6.gif'
[dcb504ed-4cac-46be-8e21-449d0e83a76f] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=202 duration=2132.23 view=8.45 db=22.70
[0497fda1-6458-428c-869f-3991cd8c98b1] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=15.87 view=3.15 db=3.35[f0e36ecc-91c4-4c55-8d04-a8f5c1081c69] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=16.64 view=3.95 db=2.90[69eac9d5-61c5-4667-a93e-43dfff583dad] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=28.60 view=6.59 db=11.34
[d984f9bd-277b-4093-bb08-015b93f2e17c] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=19.69 view=4.73 db=2.86[09e73a05-9fa2-44f0-b2d6-0837bb5dcee4] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=14.27 view=3.15 db=2.95[7cd35645-9a3e-4f06-bc68-41a77ad8b540] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=33.54 view=0.76 db=19.77
[63473f06-6ad7-4bc4-a39a-1bbd71f36aae] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=20.90 view=0.61 db=6.74
[a290837f-fe34-4d35-ba55-7363f5c2e8e5] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=10.75 view=1.38 db=3.01
[933b1eec-f68b-4e3a-9df1-9601f6005bcd] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=16.70 view=3.70 db=2.99[8b2e2832-824d-4347-9393-b71797aee3ee] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=14.41 view=3.20 db=2.73[ed9e958c-6980-49a4-b036-cfcf2135e6d5] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=21.12 view=0.73 db=5.38[0a96967e-7a88-4660-b7bf-ce54341998ad] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=18.24 view=0.64 db=5.37
[ddc5dd8d-a885-4f6e-85a2-2b34c9f74e09] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=9.25 view=1.18 db=2.33
[cde0bf8e-646c-40bf-902a-a1cfb199b88e] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=12.49 view=2.95 db=1.91[8525a889-5486-40e3-8ee1-f79f933b39e5] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=12.66 view=2.85 db=1.97[2a382ebf-f6d3-415f-888c-a539306177c8] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=15.90 view=4.14 db=2.16[febe5497-4aaa-490f-8595-4e7b747382cc] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=16.13 view=4.14 db=2.36[a99b56c0-4ada-4db7-b407-615fa8f58562] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=206 duration=15.07 view=3.73 db=2.09[ef30d04d-c46e-4409-a5ab-7c900496af55] method=GET path=/api/v1/media/105572453435486980 format=html controller=Api::V1::MediaController action=show status=422 duration=11.29 view=1.14 db=1.90[b21a081f-9fe7-4358-86ca-ec14497902cd] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=19.26 view=1.06 db=4.99[c71a2c62-2519-4848-88f4-a93935fa8b48] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=21.14 view=0.67 db=6.63
[0b200547-8b54-4fb2-90cf-79de87896add] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=11.40 view=1.46 db=2.87
[1631b8b5-c6fd-433d-b1fa-9e6690cd6851] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=20.91 view=0.82 db=6.26[17d64c89-2416-4d77-8425-cd334c259b82] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=18.70 view=0.70 db=5.28
[7072f54f-d127-4931-8ba1-1a69e3d62a6e] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=9.28 view=1.26 db=2.39
[2f212057-a10f-49a0-bcbc-6168b55597b6] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=23.36 view=1.49 db=5.32[a9c7277d-9e8e-49f7-99ff-9136bcce9222] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=24.73 view=0.79 db=7.49
[c20fcd4f-b1d3-42f1-a143-03e6c8be9dc6] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=10.45 view=1.38 db=2.25
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] [paperclip] Trying to link /tmp/RackMultipart20210117-20-1er9a2n.png to /tmp/c897b815bb15893167787aeb040013da20210117-20-147wkbm.png
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] [paperclip] Trying to link /tmp/c897b815bb15893167787aeb040013da20210117-20-147wkbm.png to /tmp/4d8bb45b953148f086dac8c44784031920210117-20-1m3ifum.png [1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] Command :: file -b --mime '/tmp/4d8bb45b953148f086dac8c44784031920210117-20-1m3ifum.png'
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] Command :: identify -format %m '/tmp/c897b815bb15893167787aeb040013da20210117-20-147wkbm.png[0]'
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] Command :: convert '/tmp/c897b815bb15893167787aeb040013da20210117-20-147wkbm.png[0]' -auto-orient -resize "400x400>" -quality 90 -strip +set modify-date +set create-date '/tmp/e98ef0377f8ed47c9830012fa40941f420210117-20-k65lhd'
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] Command :: convert '/tmp/e98ef0377f8ed47c9830012fa40941f420210117-20-k65lhd' RGB:-
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] [paperclip] Trying to link /tmp/e98ef0377f8ed47c9830012fa40941f420210117-20-k65lhd to /tmp/ece905559e2fbc1353a9feb62255104420210117-20-oqu9ki
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] [paperclip] Trying to link /tmp/c897b815bb15893167787aeb040013da20210117-20-147wkbm.png to /tmp/4d8bb45b953148f086dac8c44784031920210117-20-1bdt1i1.png [1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] Command :: file -b --mime '/tmp/4d8bb45b953148f086dac8c44784031920210117-20-1bdt1i1.png'
[1fd7ae3c-38be-4625-8a2c-f98c1c8880f6] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=202 duration=652.13 view=6.73 db=17.45
[cc36fcd8-1ffe-4625-a4f5-51a30731c329] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=15.35 view=3.83 db=2.02[401a8e38-c191-45e3-ac85-ec4400097921] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=14.47 view=3.40 db=1.98[3c06b836-39f8-48e5-98ad-48bef58b8a59] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=13.18 view=3.23 db=1.95[833961d6-5dbf-4b79-81bb-8ae827725fe4] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=14.63 view=3.58 db=1.99[eca4a5b5-647c-4f28-b906-17fc080489fe] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=27.39 view=1.46 db=7.01[84c578cc-269f-4351-8b92-f79cb01894ab] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=21.90 view=0.77 db=6.92
[5b4d8592-3a08-43c2-9b06-22d6a76a7405] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=10.78 view=1.33 db=2.80
[ec3e7a20-bc11-4ea9-a819-529c6570925d] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=13.11 view=3.20 db=1.92[e1ed91a1-b27c-4c79-937c-b44cd1149b5c] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=17.53 view=4.35 db=2.70[d9b2058b-0500-46bd-b0e9-bae3c613454b] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=15.19 view=3.27 db=2.05[d679d43e-20b4-4ab7-940b-58c848d1953f] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=14.32 view=3.41 db=1.98[557948ee-48a5-417f-9a90-e0916b515d2c] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=13.10 view=3.09 db=1.95[545e1bb4-90cc-4a4f-a875-cee7bf701a99] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=16.23 view=5.30 db=2.02[a3999dac-20c1-49da-94bb-9674cba68d60] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=21.84 view=0.84 db=7.10[d2aabf4d-254f-47cc-9888-9d5cff9c75f6] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=18.99 view=0.69 db=5.42
[fd9d96da-9863-45cf-b00f-7f3d060d46fb] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=10.13 view=1.49 db=2.14
[09e59d0a-155c-4027-b329-778d73c03d26] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=15.31 view=3.73 db=2.21[ca25fbca-9486-4012-ba19-2e256f8e937b] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=13.72 view=3.24 db=2.15[f0ff518d-a866-4a7e-a8a3-4bcc7a309f6f] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=30.76 view=6.23 db=14.18
[0655231e-0607-4662-8266-23d72ca160f2] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=16.42 view=3.70 db=2.54[5aaf431e-9cbb-4eeb-b8c0-1785fec22ed1] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=17.11 view=4.29 db=2.10[935b3aba-3c5e-4656-98fb-7318b67764ef] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=13.40 view=3.14 db=2.23[152b6c50-98c8-45ee-a781-983921b113ae] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=206 duration=14.09 view=3.36 db=2.13[611ac046-656c-44a4-930d-50d66199d86b] method=GET path=/api/v1/media/105572458437971750 format=html controller=Api::V1::MediaController action=show status=422 duration=10.49 view=0.72 db=1.90
```

**Comment by kgnfth** [comment]
Did u follow the instruction starting from https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/mastodon.yml#L187

**Comment by icarusredux** [comment]
I did, yeah.

I'm able to change my avatar and banner picture just fine, it's during the transcode/thumbnail generation part for media uploads that we're seeing the issue.

**Comment by kgnfth** [comment]
I will check it later as i have no time right now
