### ISSUE TITLE
Ghost one click app won't connect to database

### ISSUE THREAD

**Issue by askasp** [caprover/one-click-apps#555]
I made the ghost one click app, but it just hangs on connecting to the mariadb. 
Logs and configs added below. Please let me know if you need any more info. I also tried using a newer version of ghost without prevail..
I think it has something to do with caprover docker internal DNS

Output from container logs on db

`mariadb 13:30:08.42
mariadb 13:30:08.51 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 13:30:08.53 INFO  ==> Initializing mariadb database
mariadb 13:30:08.56 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 13:30:08.57 INFO  ==> Setting user option
mariadb 13:30:08.59 INFO  ==> Using persisted data
mariadb 13:30:08.66 INFO  ==> Running mysql_upgrade
mariadb 13:30:08.68 INFO  ==> Starting mariadb in background`

output from ghost container 

`nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server`

My ghost config 

`GHOST_DATABASE_NAME=ghost
GHOST_DATABASE_PASSWORD=stestpw
GHOST_DATABASE_USER=ghost
GHOST_EMAIL=akselkjetsa@gmail.com
GHOST_HOST=blog.akselerasjon.no
GHOST_PASSWORD=slangebrille22
GHOST_PROTOCOL=http
GHOST_PORT_NUMBER=80
MARIADB_HOST=srv-captain--newghost-db
MARIADB_PORT_NUMBER=3306
SMTP_FROM_ADDRESS=your_email@gmail.com
SMTP_HOST=smtp.gmail.com
SMTP_PASSWORD=testpw2
SMTP_PORT=465
SMTP_SERVICE=GMail
SMTP_USER=your_email@gmail.com`

my mariadb config 

`MARIADB_DATABASE=ghost
MARIADB_PASSWORD=testpw
MARIADB_ROOT_PASSWORD=testpw
MARIADB_ROOT_USER=admin
MARIADB_USER=ghost`

**Comment by githubsaturn** [comment]
I just tried this and it worked just fine with all default values:
```
2021-11-06T14:51:05.256020829Z 
2021-11-06T14:51:05.256090171Z Welcome to the Bitnami ghost container
2021-11-06T14:51:05.256095280Z Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
2021-11-06T14:51:05.256100691Z Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
2021-11-06T14:51:05.256104257Z 
2021-11-06T14:51:09.503821920Z nami    INFO  Initializing mysql-client
2021-11-06T14:51:09.565922237Z nami    INFO  mysql-client successfully initialized
2021-11-06T14:51:14.596304416Z nami    INFO  Initializing ghost
2021-11-06T14:51:14.849672793Z handler WARN  Using /opt/bitnami/ghost as working directory
2021-11-06T14:51:14.888980689Z mysql-c INFO  Trying to connect to MySQL server
2021-11-06T14:51:46.152332447Z mysql-c INFO  Found MySQL server listening at srv-captain--ghost-db:3306
2021-11-06T14:51:46.188515229Z mysql-c INFO  MySQL server listening and working at srv-captain--ghost-db:3306
2021-11-06T14:51:46.192731534Z ghost   INFO  ==> Configuring Database...
2021-11-06T14:51:46.204075705Z ghost   INFO  ==> Configuring Ghost...
2021-11-06T14:51:48.895034411Z ghost   INFO  ==> Configuring host...
2021-11-06T14:51:48.902333612Z ghost   INFO  ==> Restarting service...
2021-11-06T14:51:56.048925544Z ghost   INFO  ==> Host configured successfully!
2021-11-06T14:51:56.075400509Z ghost   INFO  ==> Configuring SMTP...
2021-11-06T14:51:56.079773871Z ghost   INFO  ==> Creating admin user...
2021-11-06T14:52:17.239128362Z ghost   INFO  The admin user was created
2021-11-06T14:52:19.474482929Z ghost   INFO 
2021-11-06T14:52:19.474894116Z ghost   INFO  ########################################################################
2021-11-06T14:52:19.475177159Z ghost   INFO   Installation parameters for ghost:
2021-11-06T14:52:19.476005041Z ghost   INFO     Email: youremail@example.com
2021-11-06T14:52:19.476455370Z ghost   INFO     Password: **********
2021-11-06T14:52:19.476805902Z ghost   INFO   (Passwords are not shown for security reasons)
2021-11-06T14:52:19.477152806Z ghost   INFO  ########################################################################
2021-11-06T14:52:19.477485333Z ghost   INFO 
2021-11-06T14:52:19.477865571Z nami    INFO  ghost successfully initialized
2021-11-06T14:52:19.507074255Z INFO  ==> Starting ghost... 
2021-11-06T14:52:20.860552277Z [14:52:20] Ensuring user is not logged in as ghost user [started]
2021-11-06T14:52:20.862948388Z [14:52:20] Ensuring user is not logged in as ghost user [skipped]
2021-11-06T14:52:20.873564346Z [14:52:20] Checking if logged in user is directory owner [started]
2021-11-06T14:52:20.874271620Z [14:52:20] Checking if logged in user is directory owner [skipped]
2021-11-06T14:52:20.883987260Z [14:52:20] Checking current folder permissions [started]
2021-11-06T14:52:20.891369286Z [14:52:20] Checking current folder permissions [completed]
2021-11-06T14:52:20.904765788Z [14:52:20] Validating config [started]
2021-11-06T14:52:20.923024305Z [14:52:20] Validating config [completed]
2021-11-06T14:52:20.958111229Z [14:52:20] Checking memory availability [started]
2021-11-06T14:52:20.978281612Z [14:52:20] Checking memory availability [completed]
2021-11-06T14:52:20.980951138Z - Starting Ghost
2021-11-06T14:52:25.355192983Z ✔ Starting Ghost
2021-11-06T14:52:25.357429061Z 
2021-11-06T14:52:25.357473635Z ------------------------------------------------------------------------------
2021-11-06T14:52:25.357904037Z 
2021-11-06T14:52:25.357924275Z Your admin interface is located at: 
2021-11-06T14:52:25.357929565Z 
2021-11-06T14:52:25.357935717Z     http://blog.example.com/ghost/
2021-11-06T14:52:25.357939884Z 
2021-11-06T14:52:25.372492980Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":113,"level":30,"msg":"Your blog is now available on http://blog.example.com/ ","time":"2021-11-06T14:52:10.295Z","v":0}
2021-11-06T14:52:25.372541101Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":113,"level":30,"msg":"Ctrl+C to shut down ","time":"2021-11-06T14:52:10.296Z","v":0}
2021-11-06T14:52:25.372549987Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":113,"level":30,"msg":"Ghost boot 18.502s ","time":"2021-11-06T14:52:10.313Z","v":0}
2021-11-06T14:52:25.372561429Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":113,"level":50,"req":{"meta":{"requestId":"22c2d2f0-3f11-11ec-96ce-8153c83a9d89","userId":null},"url":"/authentication/setup/?setup%5B0%5D%5Bname%5D=user&setup%5B0%5D%5Bemail%5D=youremail@example.com&setup%5B0%5D%5Bpassword%5D=ghostasfsadfasdfasfa33242&setup%5B0%5D%5BblogTitle%5D=User's%20Blog","method":"POST","originalUrl":"/ghost/api/v0.1/authentication/setup/?setup%5B0%5D%5Bname%5D=user&setup%5B0%5D%5Bemail%5D=youremail@example.com&setup%5B0%5D%5Bpassword%5D=ghostasfsadfasdfasfa33242&setup%5B0%5D%5BblogTitle%5D=User's%20Blog","params":{},"headers":{"host":"127.0.0.1:2368","connection":"close","content-length":"0"},"body":{},"query":{"setup":{"0":{"name":"user","email":"youremail@example.com","blogTitle":"User's Blog"}}}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","content-type":"application/json; charset=utf-8","content-length":"100","etag":"W/\"64-AzQ+6cLmip1ffIeFOtW3Q36ja+s\"","vary":"Accept-Encoding"},"statusCode":422,"responseTime":"46ms"},"err":{"id":"22c8ed70-3f11-11ec-96ce-8153c83a9d89","domain":"http://blog.example.com","code":null,"name":"ValidationError","statusCode":422,"level":"normal","message":"Sorry, you cannot use an insecure password.","stack":"ValidationError: Sorry, you cannot use an insecure password.\n    at new ValidationError (/opt/bitnami/ghost/versions/2.16.4/node_modules/ghost-ignition/lib/errors/index.js:121:23)\n    at Function.setup (/opt/bitnami/ghost/versions/2.16.4/core/server/models/user.js:612:35)\n    at Child.User.findOne.then (/opt/bitnami/ghost/versions/2.16.4/core/server/api/v0.1/authentication.js:88:25)\n    at Child.tryCatcher (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/opt/bitnami/ghost/versions/2.16.4/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)"},"msg":"Sorry, you cannot use an insecure password.","time":"2021-11-06T14:52:17.232Z","v":0}
2021-11-06T14:52:25.372614469Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":113,"level":40,"msg":"Ghost has shut down ","time":"2021-11-06T14:52:18.586Z","v":0}
2021-11-06T14:52:25.372622004Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":40,"msg":"Theme's file locales/en.json not found. ","time":"2021-11-06T14:52:24.629Z","v":0}
2021-11-06T14:52:25.372628676Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"msg":"Ghost is running in production... ","time":"2021-11-06T14:52:25.339Z","v":0}
2021-11-06T14:52:25.372635048Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"msg":"Your blog is now available on http://blog.example.com/ ","time":"2021-11-06T14:52:25.340Z","v":0}
2021-11-06T14:52:25.372641931Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"msg":"Ctrl+C to shut down ","time":"2021-11-06T14:52:25.341Z","v":0}
2021-11-06T14:52:25.372648063Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"msg":"Ghost boot 3.179s ","time":"2021-11-06T14:52:25.344Z","v":0}
2021-11-06T14:52:53.376857377Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"req":{"meta":{"requestId":"37d96230-3f11-11ec-ae0c-fbadc51d3c77","userId":null},"url":"/","method":"GET","originalUrl":"/","params":{},"headers":{"host":"ghost.********.com","x-real-ip":"98.207.72.88","x-forwarded-for":"98.207.72.88","x-forwarded-proto":"http","connection":"close","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,fa-IR;q=0.6,fa;q=0.5,es-US;q=0.4,es;q=0.3,fr-CA;q=0.2,fr;q=0.1"},"body":{},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"public, max-age=0","content-type":"text/html; charset=utf-8","etag":"W/\"54d5-cOS3sDZe8xcaqjS8JW+J9eXNbpU\"","vary":"Accept-Encoding","content-encoding":"gzip"},"statusCode":200,"responseTime":"779ms"},"msg":"","time":"2021-11-06T14:52:53.342Z","v":0}
2021-11-06T14:52:54.376814839Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"req":{"meta":{"requestId":"386dda00-3f11-11ec-ae0c-fbadc51d3c77","userId":null},"url":"/assets/built/screen.css?v=42539e4f42","method":"GET","originalUrl":"/assets/built/screen.css?v=42539e4f42","params":{},"headers":{"host":"ghost.*****.com","x-real-ip":"98.207.72.88","x-forwarded-for":"98.207.72.88","x-forwarded-proto":"http","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","accept":"text/css,*/*;q=0.1","referer":"http://ghost.********.com/","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,fa-IR;q=0.6,fa;q=0.5,es-US;q=0.4,es;q=0.3,fr-CA;q=0.2,fr;q=0.1"},"body":{},"query":{"v":"42539e4f42"}},"res":{"_headers":{"x-powered-by":"Express","accept-ranges":"bytes","cache-control":"public, max-age=31536000","last-modified":"Sat, 26 Oct 1985 08:15:00 GMT","etag":"W/\"8a14-7438674ba0\"","content-type":"text/css; charset=UTF-8","vary":"Accept-Encoding","content-encoding":"gzip"},"statusCode":200,"responseTime":"14ms"},"msg":"","time":"2021-11-06T14:52:53.550Z","v":0}
2021-11-06T14:52:54.376862038Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"req":{"meta":{"requestId":"38733130-3f11-11ec-ae0c-fbadc51d3c77","userId":null},"url":"/assets/built/jquery.fitvids.js?v=42539e4f42","method":"GET","originalUrl":"/assets/built/jquery.fitvids.js?v=42539e4f42","params":{},"headers":{"host":"ghost.******.com","x-real-ip":"98.207.72.88","x-forwarded-for":"98.207.72.88","x-forwarded-proto":"http","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","accept":"*/*","referer":"http://ghost.*****.com/","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,fa-IR;q=0.6,fa;q=0.5,es-US;q=0.4,es;q=0.3,fr-CA;q=0.2,fr;q=0.1"},"body":{},"query":{"v":"42539e4f42"}},"res":{"_headers":{"x-powered-by":"Express","accept-ranges":"bytes","cache-control":"public, max-age=31536000","last-modified":"Sat, 26 Oct 1985 08:15:00 GMT","etag":"W/\"778-7438674ba0\"","content-type":"application/javascript; charset=UTF-8","vary":"Accept-Encoding","content-encoding":"gzip"},"statusCode":200,"responseTime":"6ms"},"msg":"","time":"2021-11-06T14:52:53.577Z","v":0}
2021-11-06T14:52:54.376878790Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"req":{"meta":{"requestId":"3897a920-3f11-11ec-ae0c-fbadc51d3c77","userId":null},"url":"/assets/built/infinitescroll.js?v=42539e4f42","method":"GET","originalUrl":"/assets/built/infinitescroll.js?v=42539e4f42","params":{},"headers":{"host":"ghost.******.com","x-real-ip":"98.207.72.88","x-forwarded-for":"98.207.72.88","x-forwarded-proto":"http","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","accept":"*/*","referer":"http://ghost.******.com/","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,fa-IR;q=0.6,fa;q=0.5,es-US;q=0.4,es;q=0.3,fr-CA;q=0.2,fr;q=0.1"},"body":{},"query":{"v":"42539e4f42"}},"res":{"_headers":{"x-powered-by":"Express","accept-ranges":"bytes","cache-control":"public, max-age=31536000","last-modified":"Sat, 26 Oct 1985 08:15:00 GMT","etag":"W/\"3f1-7438674ba0\"","content-type":"application/javascript; charset=UTF-8","content-length":1009,"vary":"Accept-Encoding"},"statusCode":200,"responseTime":"5ms"},"msg":"","time":"2021-11-06T14:52:53.816Z","v":0}
2021-11-06T14:52:54.376905089Z {"name":"Log","hostname":"2fb02b2ba2f6","pid":193,"level":30,"req":{"meta":{"requestId":"38e5a210-3f11-11ec-ae0c-fbadc51d3c77","userId":null},"url":"/favicon.ico","method":"GET","originalUrl":"/favicon.ico","params":{},"headers":{"host":"ghost.*******.com","x-real-ip":"98.207.72.88","x-forwarded-for":"98.207.72.88","x-forwarded-proto":"http","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","referer":"http://ghost.******.com/","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,fa-IR;q=0.6,fa;q=0.5,es-US;q=0.4,es;q=0.3,fr-CA;q=0.2,fr;q=0.1"},"body":{},"query":{}},"res":{"_headers":{"x-powered-by":"Express","content-type":"image/x-icon","etag":"\"36e47e74810a0d8c32a77f495c49cf8e\"","cache-control":"public, max-age=86400","vary":"Accept-Encoding","content-encoding":"gzip"},"statusCode":200,"responseTime":"6ms"},"msg":"","time":"2021-11-06T14:52:54.328Z","v":0}
```

**Comment by matbgn** [comment]
Solved by #670
